#!/bin/bash

DATASETS=("NK_B" "Monocyte_NK" "Monocyte_B")
CPG_FILE="/mnt/analysis/derbelh/CpG_Without_Strand.bed"
TARGET_COL=5
MIN_CPG=10  # Set to 10 based on standard regulatory region thresholds

for DS in "${DATASETS[@]}"; do
    DIR="results"
    INPUT_BED="$DIR/${DS}_benchmark_3_tools.csv"
    TMP_CENTER="$DIR/center_tmp.bed"
    TMP_OUT="$DIR/${DS}_benchmark_3_tools_tmp.csv"

    awk 'BEGIN{OFS="\t"} {
        s=$3-$2; 
        if(s<1000){
            c=int(($2+$3)/2); 
            start=c-500; 
            end=c+500; 
            if(start<0) start=0; 
            $2=start; 
            $3=end
        } 
        print $0
    }' "$INPUT_BED" | bedtools intersect -a - -b "$CPG_FILE" -c > "$TMP_CENTER"

    awk -v col="$TARGET_COL" -v n="$MIN_CPG" -v orig_file="$INPUT_BED" 'BEGIN {FS="\t"; OFS="\t"} {
        # Read the original un-expanded file line-by-line in sync
        getline line_orig < orig_file; 
        split(line_orig, a_orig, "\t");
        orig_s = a_orig[2]; 
        orig_e = a_orig[3];

        # The CpG count generated by bedtools is in the TARGET_COL
        cpg_count = $col + 0;

        # If the region passes the threshold, output it
        if (cpg_count >= n) {
            # Restore the original un-expanded start/end coordinates
            $2 = orig_s;
            $3 = orig_e;
            
            # Print only the original columns (dropping the bedtools count column)
            for (i=1; i<col; i++) {
                printf "%s%s", $i, (i==col-1 ? "" : OFS)
            }
            print ""
        }
    }' "$TMP_CENTER" > "$TMP_OUT"

    mv "$TMP_OUT" "$INPUT_BED"
    rm "$TMP_CENTER"
    
    echo "Finished filtering $DS..."
done
